import { Page } from '../page';
/**
 * 项目档案主表
 */
export class ProjectManageArchives extends Page{
    id?:string;
    //"项目立项档案id"
    proId?:string;
    //项目编码(来自项目立项)
    proCode?:string;
    //项目名称(来自项目立项)
    proName?:string;
    //客户档案id
    cusId?:string;
    //客户编码(来自客户档案)
    cusCode?:string;
    //客户名称(来自客户档案)
    cusName?:string;
    //项目总金额
    totalPrice?:number;
    //已回款金额
    received?:number;
    //销售经理id
    saleManagerId?:string;
    //销售经理
    saleManager?:string;
    //业务员id
    saleManId?:string;
    //业务员
    saleMan?:string;
    //实施项目经理id
    impManagerId?:string;
    //实施项目经理
    impManager?:string;
    //实施顾问id
    impConsultantId?:string;
    //实施顾问
    impConsultant?:string;
    //实施所有人员id(用于前台交互)
    impConsultantList?:any[];
    //开发项目经理id
    deManagerId?:string;
    //开发项目经理
    deManager?:string;
    //开发工程师id
    deEngineerId?:string;
    //开发工程师
    deEngineer?:string;
    //开发所有人员id(用于前台交互)
    deEngineerList?:any[];
    //服务经理id
    seManagerId?:string;
    //服务经理
    seManager?:string;
    //服务工程师id
    seEngineerId?:string;
    //服务工程师
    seEngineer?:string;
    //服务所有人员id(用于前台交互)
    seEngineerList?:any[];
    //组织
    pkOrg?:string;
    //里程碑类型id
    milestoneId?:string;
    //里程碑类型名称
    milestoneType?:string;
    //商务
    bsInfo?:{}
    //实施
    ipInfo?:{}
    //开发
    deInfo?:{}
    //服务
    seInfo?:{}
    //类型
    planType?:string;
    //合同档案id
    contractFileId?:string;
}
